### ISSUE TITLE
Ghosting bug

### ISSUE THREAD

**Issue by JustBru00** [FrostHexABG/TimingSystem#37]
[18:34:31 INFO]: [The_Lasersloth: Set Abgestochen's game mode to Spectator Mode]
[18:34:31 WARN]: [TimingSystem] Task #353780 for TimingSystem v2.3-SNAPSHOT generated an exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.isInsideVehicle()" because "player" is null
        at me.makkuusen.timing.system.loneliness.GhostingController.isPlayerInBoat(GhostingController.java:91) ~[TimingSystem-2.3-SNAPSHOT.jar:?]
        at me.makkuusen.timing.system.loneliness.GhostingController.updateBoatVisibilityToSpecificDriver(GhostingController.java:79) ~[TimingSystem-2.3-SNAPSHOT.jar:?]
        at me.makkuusen.timing.system.loneliness.GhostingController.lambda$updateAllGhostedToPlayer$3(GhostingController.java:64) ~[TimingSystem-2.3-SNAPSHOT.jar:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at me.makkuusen.timing.system.loneliness.GhostingController.updateAllGhostedToPlayer(GhostingController.java:64) ~[TimingSystem-2.3-SNAPSHOT.jar:?]
        at me.makkuusen.timing.system.loneliness.GhostingController.lambda$onVehicleExit$5(GhostingController.java:117) ~[TimingSystem-2.3-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1479) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1393) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1170) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[18:34:31 INFO]: Phillonoo issued server command: /gamemode creative

**Comment by JustBru00** [comment]
Duplicate of #36
