### ISSUE TITLE
Error in events

### ISSUE THREAD

**Issue by JustBru00** [FrostHexABG/TimingSystem#47]
```
[01:18:19 ERROR]: [TimingSystem] [ACF] Exception in command: event 
[01:18:19 ERROR]: [TimingSystem] [ACF] java.lang.NullPointerException: Cannot invoke "me.makkuusen.timing.system.tplayer.TPlayer.getNameDisplay()" because the return value of "me.makkuusen.timing.system.database.TSDatabase.getPlayer(java.util.UUID)" is null
[01:18:19 ERROR]: [TimingSystem] [ACF]  at TimingSystem-2.3-SNAPSHOT.jar//me.makkuusen.timing.system.commands.CommandEvent.onListEvents(CommandEvent.java:72)
[01:18:19 ERROR]: [TimingSystem] [ACF]  at TimingSystem-2.3-SNAPSHOT.jar//me.makkuusen.timing.system.commands.CommandEvent.onActiveEvents(CommandEvent.java:57)
[01:18:19 ERROR]: [TimingSystem] [ACF]  at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[01:18:19 ERROR]: [TimingSystem] [ACF]  at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[01:18:19 ERROR]: [TimingSystem] [ACF]  at TimingSystem-2.3-SNAPSHOT.jar//me.makkuusen.timing.system.acf.RegisteredCommand.invoke(RegisteredCommand.java:152)
[01:18:19 ERROR]: [TimingSystem] [ACF]  at TimingSystem-2.3-SNAPSHOT.jar//me.makkuusen.timing.system.acf.BaseCommand.executeCommand(BaseCommand.java:578)
[01:18:19 ERROR]: [TimingSystem] [ACF]  at TimingSystem-2.3-SNAPSHOT.jar//me.makkuusen.timing.system.acf.BaseCommand.execute(BaseCommand.java:513)
[01:18:19 ERROR]: [TimingSystem] [ACF]  at TimingSystem-2.3-SNAPSHOT.jar//me.makkuusen.timing.system.acf.RootCommand.execute(RootCommand.java:99)
[01:18:19 ERROR]: [TimingSystem] [ACF]  at TimingSystem-2.3-SNAPSHOT.jar//me.makkuusen.timing.system.acf.BukkitRootCommand.execute(BukkitRootCommand.java:84)
[01:18:19 ERROR]: [TimingSystem] [ACF]  at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91)
[01:18:19 ERROR]: [TimingSystem] [ACF]  at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
[01:18:19 ERROR]: [TimingSystem] [ACF]  at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31)
[01:18:19 ERROR]: [TimingSystem] [ACF]  at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19)
[01:18:19 ERROR]: [TimingSystem] [ACF]  at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8)
[01:18:19 ERROR]: [TimingSystem] [ACF]  at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5)
[01:18:19 ERROR]: [TimingSystem] [ACF]  at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103)
[01:18:19 ERROR]: [TimingSystem] [ACF]  at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:443)
[01:18:19 ERROR]: [TimingSystem] [ACF]  at net.minecraft.commands.Commands.performCommand(Commands.java:350)
[01:18:19 ERROR]: [TimingSystem] [ACF]  at net.minecraft.commands.Commands.performCommand(Commands.java:337)
[01:18:19 ERROR]: [TimingSystem] [ACF]  at net.minecraft.commands.Commands.performCommand(Commands.java:332)
[01:18:19 ERROR]: [TimingSystem] [ACF]  at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2218)
[01:18:19 ERROR]: [TimingSystem] [ACF]  at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$11(ServerGamePacketListenerImpl.java:2192)
[01:18:19 ERROR]: [TimingSystem] [ACF]  at net.minecraft.server.TickTask.run(TickTask.java:18)
[01:18:19 ERROR]: [TimingSystem] [ACF]  at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[01:18:19 ERROR]: [TimingSystem] [ACF]  at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[01:18:19 ERROR]: [TimingSystem] [ACF]  at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1535)
[01:18:19 ERROR]: [TimingSystem] [ACF]  at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201)
[01:18:19 ERROR]: [TimingSystem] [ACF]  at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[01:18:19 ERROR]: [TimingSystem] [ACF]  at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1512)
[01:18:19 ERROR]: [TimingSystem] [ACF]  at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1505)
[01:18:19 ERROR]: [TimingSystem] [ACF]  at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
[01:18:19 ERROR]: [TimingSystem] [ACF]  at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1464)
[01:18:19 ERROR]: [TimingSystem] [ACF]  at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1471)
[01:18:19 ERROR]: [TimingSystem] [ACF]  at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1316)
[01:18:19 ERROR]: [TimingSystem] [ACF]  at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
[01:18:19 ERROR]: [TimingSystem] [ACF]  at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by JustBru00** [comment]
> Do you know in what situation this happened?

I think it was related to a player being offline while using something in /event

**Comment by JustBru00** [comment]
May be duplicate of #48
